use_frameworks!

platform :ios, '11.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

end

# 模拟器忽略 arm64
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end